48 1.8 choose kind of event
hpi-swt2/workshop-portal pull request #105
Opened 2016-11-30 14:22 UTC by bjrne

2016-11-30 15:32 UTC, Baschdl commented
I think the update of db/seeds.rb is missing

2016-11-30 18:46 UTC, cmfcmf reviewed
I had some minor thoughts on this :)

2016-11-30 18:46 UTC, cmfcmf commented on app/views/events/show.html.erb
> +  <h1><%= @event.kind.humanize %> <%=t '.title', :default => model_class.model_name.human.titleize %></h1>
This only works because "Workshop" and "Camp" are spelled the same in English and German.

2016-11-30 18:46 UTC, cmfcmf commented on spec/features/event_spec.rb
> +    end
The above could be simplified by a loop like done for roles here: https://github.com/hpi-swt2/workshop-portal/blob/dev/spec/models/ability_spec.rb#L7

2016-11-30 18:46 UTC, cmfcmf commented on spec/features/event_spec.rb
> +  end
The test above could also benefit from the same loop.

2016-11-30 19:10 UTC, cmfcmf commented
> I think the update of db/seeds.rb is missing

Not necessarily, because `kind` has a default value.

2016-11-30 20:21 UTC, tom95 commented
Thanks @cmfcmf, I added the loops. `kind.humanize` should be okay for this sprint, as translations were not a requirement so far

2016-12-01 17:39 UTC, MasterCarl commented on app/views/events/_form.html.erb
> +          <%= key.humanize %>
Shouldn't the radio button be selected if the class 'active' is set for the label? Or am I missing something here?

2016-12-01 17:44 UTC, MasterCarl commented on app/views/events/_form.html.erb
> +          <%= key.humanize %>
I just checked in my browser, it seems to work

2016-12-01 17:47 UTC, MasterCarl requested changes
This PR looks good so far, but I think the kind of event should also be displayed on the index page

2016-12-01 17:47 UTC, MasterCarl commented on app/views/events/show.html.erb
> +  <h1><%= @event.kind.humanize %> <%=t '.title', :default => model_class.model_name.human.titleize %></h1>
I don't think that the event kind should be the first part of the title, but it's good to have it displayed

2016-12-01 17:48 UTC, bjrne commented
@MasterCarl Isn't that what @LeaGe is working on?

2016-12-01 17:50 UTC, LeaGe commented
@bjrne yupp. :)

2016-12-01 20:14 UTC, tom95 commented on app/views/events/show.html.erb
> +  <h1><%= @event.kind.humanize %> <%=t '.title', :default => model_class.model_name.human.titleize %></h1>
I'll put it last, in parenthesis. So we would get "Mint Camp (Camp)" which is still kinda stupid, but at least explicit for the user.

2016-12-02 12:41 UTC, MasterCarl approved these changes

2016-12-02 18:26 UTC, merged