Remove id from events overview page, use name for link instead
hpi-swt2/workshop-portal pull request #133
Opened 2016-12-03 10:12 UTC by bjrne

#115 
If anyone figures out how to write a test for the routing from clicking the name of an event to the event#show page, feel free to add it or tell me how to do it.

2016-12-03 11:00 UTC, chrisma commented
@bjrne https://github.com/hpi-swt2/workshop-portal/blob/master/spec/features/user_spec.rb#L34

2016-12-06 21:17 UTC, MasterCarl requested changes

2016-12-06 21:17 UTC, MasterCarl commented on spec/features/event_spec.rb
> +      click_link "Event-Name"
I'd rather write `event.name` so that nothing breaks if someone changes the factory

2016-12-10 14:07 UTC, MasterCarl approved these changes

2016-12-10 14:14 UTC, merged