WIP: 88 2.11 fill in profile before application
hpi-swt2/workshop-portal pull request #153
Opened 2016-12-06 14:36 UTC by cmfcmf

@hefowe

2016-12-06 21:13 UTC, MasterCarl requested changes

2016-12-06 21:13 UTC, MasterCarl commented on config/locales/de.application_letters.yml
> +          experience: "Wie hast du von uns Erfahren?"
I'd use a lowercase e

2016-12-06 21:13 UTC, MasterCarl commented on spec/features/application_letters_spec.rb
> +  it "shows an error if you don't have a profile" do
I'd also mention that a redirect should happen

2016-12-11 20:51 UTC, MasterCarl approved these changes

2016-12-11 20:52 UTC, MasterCarl commented
Maybe someone from team-hendrik could add their review as well

2016-12-11 21:00 UTC, cmfcmf commented
> Maybe someone from team-hendrik could add their review as well

Whoops, forgot about this. Thank you @MasterCarl, sorry @hefowe. @nilsthamm should take a look.

2016-12-13 09:08 UTC, nilsthamm approved these changes

2016-12-13 15:48 UTC, merged