55 3.14 send emails backend
hpi-swt2/workshop-portal pull request #158
Opened 2016-12-07 22:11 UTC by frederike-ramin

Make it possible to send E-Mails via a simple method call.  
  
**IMPORTANT:** Have a look at the Wiki too, for more detailed information.

2016-12-07 22:32 UTC, Baschdl commented
I think it would be good to add the initial setup mentioned on the wiki page to the .travis.yml setup

2016-12-08 08:25 UTC, aloeser commented
@Baschdl I dont think this is a good idea/required. Figaro itself should be installed automatically via "bundle install".
The second and third line are for setting up email credentials for development and production mode. But since we dont want to send emails in tests, the tests are mocked and "deliver" the emails into an array. This is why we dont need the second and third command.
And the Heroku line is pointless without step 2 and 3, and should only executed once by someone with access rights to heroku, not with every deploy

2016-12-08 13:04 UTC, Baschdl commented
@tobiduer Do you/the POs want to try the mail functionality on heroku?

2016-12-08 13:09 UTC, tobiduer commented
@Baschdl: Yes. Please :)

2016-12-08 13:23 UTC, frederike-ramin commented
@Baschdl Why would you ask that? If course they want to try it..that's why a corresponding frontend is following by @TimBasel and @Lando-L.

2016-12-08 13:27 UTC, Baschdl commented
Then it would be great if the mail backend is automatically configured on heroku. Otherwise they can't test and show the mail functionality

2016-12-08 14:38 UTC, aloeser commented
@Baschdl As I said, this is nothing we want do in this Pull Request. We intentionally use the figaro gem to hide the email credentials. In order to get sending emails working on Heroku, someone with write access to Heroku needs to set the environment variable once. That is what I and @alexanderernst agreed on.

2016-12-08 18:13 UTC, querenker requested changes

2016-12-08 18:13 UTC, querenker commented on app/mailers/portal_mailer.rb
> +  def generic_email(hideRecipients, recipients, reply_to, subject, content)
I know, we haven't any conventions about this, but afaik it is very common in ruby to naming boolean flags with a question mark suffix. 
`hideRecipients -> hide_recipients?`

2016-12-09 13:06 UTC, querenker commented on app/mailers/portal_mailer.rb
> +  def generic_email(hideRecipients, recipients, reply_to, subject, content)
Thanks for the link :) I don't understand the reason nonetheless and for me it is even a violation of the uniform access principle. But probably there is a good reason for doing so :)

2016-12-09 13:06 UTC, querenker approved these changes

2016-12-09 15:34 UTC, ekrebs5 approved these changes

2016-12-09 22:00 UTC, merged