fix #144 eventpage consistent language and errors
hpi-swt2/workshop-portal pull request #169
Opened 2016-12-09 14:29 UTC by KBorchar

2016-12-09 17:40 UTC, bjrne commented on app/models/date_range.rb
> +      errors.add(:end_date, I18n.t("date_range.errors."))
This doesn't seem correct, does it?

2016-12-09 17:40 UTC, bjrne commented on app/views/events/index.html.erb
> +                      :data => { :confirm => t('events.confirmation_prompts.confirm_delete', :default => t("helpers.links.confirm", :default => 'Löschen kann nicht rückgängig gemacht werden!')) },
Still some german in the code, is this intentional?

2016-12-09 17:40 UTC, bjrne commented on app/views/events/participants.html.erb
> +  <%= link_to t('.back', :default => t('helpers.links.back')),
This is almost the only place you use single quotes. I'm not really familiar with what Ruby expects, but wound't it make sense to have everything the same way at least? From what I heard, Ruby prefers single quotes over double quotes whenever possible.

2016-12-11 20:48 UTC, MasterCarl commented on app/views/events/participants.html.erb
> +  <%= link_to t('.back', :default => t('helpers.links.back')),
This is what I heard as well, double quoted strings should only be used for string interpolation

2016-12-11 20:49 UTC, MasterCarl submitted a review, later dismissed
I'm adding a formal request for changes

2016-12-12 13:29 UTC, KBorchar commented on app/models/date_range.rb
> +      errors.add(:end_date, I18n.t("date_range.errors."))
Fixed now, thanks.

2016-12-12 15:17 UTC, bjrne requested changes

2016-12-12 15:17 UTC, bjrne commented on app/views/events/index.html.erb
> +        <td><%= I18n.t "events.kinds.#{event.kind}" %></td>
Did you forget this or is it necessary to have double quotes here?

2016-12-12 15:17 UTC, bjrne commented on spec/features/event_spec.rb
> +      expect(page).to have_text("Anfangs-Datum darf nicht in der Vergangenheit liegen")
single quotes?

2016-12-12 15:17 UTC, bjrne commented on spec/views/events/index.html.erb_spec.rb
> +    assert_select "td", :text => I18n.t("events.kinds.#{@event.kind}")
same as above, is this necessary?

2016-12-12 15:17 UTC, bjrne commented on config/locales/de.date_ranges.yml
> +      no_timespan: "Bitte mindestens eine Zeitspanne auswählen"
Do translations need to be double-quoted? Just because everyone obviously does it this way does not necessarily mean they needs to be.

2016-12-13 10:39 UTC, KBorchar commented on app/views/events/index.html.erb
> +        <td><%= I18n.t "events.kinds.#{event.kind}" %></td>
Tests only validate with double quotes here

2016-12-13 10:39 UTC, KBorchar commented on spec/views/events/index.html.erb_spec.rb
> +    assert_select "td", :text => I18n.t("events.kinds.#{@event.kind}")
Same as above :)

2016-12-13 10:56 UTC, bjrne approved these changes

2016-12-14 12:23 UTC, merged