34 5.2 print participant name list
hpi-swt2/workshop-portal pull request #198
Opened 2016-12-14 13:11 UTC by Raandom

2016-12-14 23:07 UTC, Blaidd-Drwg requested changes
Could you also add one or two feature tests with Capybara? It would help to make sure the UI is working as intended.

2016-12-14 23:07 UTC, Blaidd-Drwg commented on app/models/event.rb
> +    order_by = order_by == 'ASC' || order_by == 'DESC' ? order_by : 'ASC'
The ternary operator isn't really needed here. An `unless` will do:
`order_by = 'ASC' unless order_by == 'ASC' || order_by == 'DESC;`

2016-12-14 23:07 UTC, Blaidd-Drwg commented on app/controllers/events_controller.rb
> +    data.unshift(['Vorname', 'Nachname', 'Geburtsdatum', 'Allergien'])
I18n

2016-12-14 23:07 UTC, Blaidd-Drwg commented on app/models/event.rb
> +    order_by = order_by == 'ASC' || order_by == 'DESC' ? order_by : 'ASC'
By the way, why "ASC" and "DESC" in uppercase when in the documentation and in the view it's in lowercase? Am I missing something?

2016-12-14 23:07 UTC, Blaidd-Drwg commented on app/controllers/events_controller.rb
> +    default = default.merge(params)
Since you set default parameters in `application_letters_ordered` anyway, these two lines aren't needed.

2016-12-14 23:07 UTC, Blaidd-Drwg commented on app/views/events/_participants_modal.html.erb
> +    <%= form_tag(event_path(@event) + "/participants_pdf" , method: :get, class:'form') do %>
Since you added it as a member route, you can simply use `participants_pdf_event_path(@event)` instead of concatenating.

2016-12-14 23:07 UTC, Blaidd-Drwg commented on app/views/events/_participants_modal.html.erb
> +          <%= label_tag(:order_by, "Sortieren nach:") %>
I18n (I'm not gonna bother commenting every single line ;) )

2017-01-08 18:17 UTC, Blaidd-Drwg requested changes

2017-01-08 18:17 UTC, Blaidd-Drwg commented on spec/models/event_spec.rb
> +    expect(@event.application_letters_ordered('first_name','ASC')).to eq([@application1,@application2])
Still uppercase

2017-01-08 18:17 UTC, Blaidd-Drwg commented on app/controllers/events_controller.rb
> +    default = {:order_by => 'email', :order_direction => 'ASC'}
Still uppercase

2017-01-12 01:00 UTC, bjrne commented
What happened/happens here? Is this outdated now? @Blaidd-Drwg @Raandom

2017-01-12 11:04 UTC, Baschdl commented
@julisa99

2017-01-16 20:08 UTC, Blaidd-Drwg approved these changes

2017-01-16 20:11 UTC, merged