35 4.3 email lists for mailing to participants
hpi-swt2/workshop-portal pull request #199
Opened 2016-12-14 13:14 UTC by Raandom

2016-12-14 13:58 UTC, Blaidd-Drwg requested changes

2016-12-14 13:58 UTC, Blaidd-Drwg commented on spec/models/event_spec.rb
> +    event.application_letters.push(application_letter_accepted)
Since FactoryGirl saves the ApplicationLetters, they get automatically added to the Event, so lines 175-176 and 179 are unnecessary.

2016-12-14 13:58 UTC, Blaidd-Drwg commented on app/views/events/_applicants_overview.html.erb
> +      <%= link_to "E-Mail-Addressen",
Using I18n would make later localizations easier.

2016-12-14 14:22 UTC, Blaidd-Drwg commented on config/locales/de.events.yml
> +      address_list: 'E-Mail-Addressen'
Exemplary. But 'Addressen' is written with one 'd' :stuck_out_tongue_winking_eye:

2016-12-14 14:22 UTC, Blaidd-Drwg approved these changes

2016-12-14 14:23 UTC, Raandom commented on config/locales/de.events.yml
> +      address_list: 'E-Mail-Addressen'
Arg

2017-01-02 13:37 UTC, bjrne commented on spec/views/events/show.html.erb_spec.rb
> +    expect(rendered).to have_link('E-Mail-Addressen')
Doesn't this break with the internationalized version?

2017-01-02 13:39 UTC, bjrne commented on app/models/event.rb
> +    application_letters.where(status: ApplicationLetter.statuses[:accepted]).reduce('') {|list, letter| list << letter.user.email << ';'}
Wouldn't this benefit from more line breaks? I wouldn't expect a loop hidden at the end of a line.

2017-01-08 18:04 UTC, Blaidd-Drwg commented
Obsolete.

2017-01-08 18:04 UTC, closed without merging