56 2.7 application status overview closes #56
hpi-swt2/workshop-portal pull request #207
Opened 2016-12-15 13:29 UTC by nstrelow

2016-12-15 13:47 UTC, nstrelow commented
Merge Conflict because of reverting #135 
Please Revert revert or include again, before resolving this merge conflict

2016-12-15 16:23 UTC, cmfcmf requested changes
I don't think you should create another controller.

2016-12-15 16:23 UTC, cmfcmf commented on app/helpers/application_helper.rb
> +    o <<  (menu_item t(:my_events, scope: 'navbar'), my_events_path)
Unnecessary whitespace added behind `<<`

2016-12-15 16:23 UTC, cmfcmf commented on app/models/application_letter.rb
> +  validates :vegeterian, :vegan, :allergic, exclusion: {in: [nil]}
I don't think you should remove the whitespace.

2016-12-15 16:23 UTC, cmfcmf commented on app/views/my_events/index.html.erb
> +      <tr>
This looks like it's indented two spaces too wide.

2016-12-15 16:23 UTC, cmfcmf commented on app/views/my_events/index.html.erb
> +      <tr>
This looks like it's indented two spaces too wide.

2016-12-15 16:23 UTC, cmfcmf commented on app/views/my_events/index.html.erb
> +    event = Event.find(letter.event_id)
This will issue another SQL query for every event.

2016-12-15 16:23 UTC, cmfcmf commented on spec/factories/application_letters.rb
> +
Can be removed

2016-12-15 16:23 UTC, cmfcmf commented on app/controllers/my_events_controller.rb
> +end
I don't think another controller is needed for this.

2016-12-18 15:54 UTC, nstrelow commented
Will start from scratch for that

2016-12-18 15:54 UTC, closed without merging