146 cons german profilinfo page
hpi-swt2/workshop-portal pull request #226
Opened 2016-12-28 16:11 UTC by radscheit

2017-01-02 14:19 UTC, Blaidd-Drwg requested changes

2017-01-02 14:19 UTC, Blaidd-Drwg commented on config/locales/de.devise.yml
> +      leave_blank_if_you_don_t_want_to_change_it: "Offen lassen, falls du dein Passwort jetzt nicht verändern möchtest."
Why "offen" and not "leer"? This would have confused me.

2017-01-02 14:19 UTC, Blaidd-Drwg commented on config/locales/de.devise.yml
> +        other: "<span style='text-transform:uppercase'>%{resource}</span> konnte nicht gespeichert werden: %{count} Fehler. Bitte korrigiere deine Eingaben um fortzufahren."
Have you tested this in your browser? I think I18n escapes HTML tags by default, in which case this would not work.

2017-01-02 14:19 UTC, Blaidd-Drwg commented on config/locales/de.devise.yml
> +        other: "<span style='text-transform:uppercase'>%{resource}</span> konnte nicht gespeichert werden: %{count} Fehler. Bitte korrigiere deine Eingaben um fortzufahren."
Also missing a comma before the "um" in both lines

2017-01-02 14:19 UTC, Blaidd-Drwg commented on spec/features/user_spec.rb
> +  scenario "User is not able to change email on user settings page" do
Why "is not"?

2017-01-02 14:19 UTC, Blaidd-Drwg commented on spec/views/navbar_spec.rb
>        expect(rendered).to have_css(".nav .dropdown-menu a", text: 'Ausloggen')
These should all use I18n

2017-01-03 22:41 UTC, radscheit commented on config/locales/de.devise.yml
> +      leave_blank_if_you_don_t_want_to_change_it: "Offen lassen, falls du dein Passwort jetzt nicht verändern möchtest."
Geschmacksfrage, aber mir nicht wichtig. Ich schreibe leer.

2017-01-03 23:02 UTC, radscheit commented on spec/views/navbar_spec.rb
>        expect(rendered).to have_css(".nav .dropdown-menu a", text: 'Ausloggen')
Good idea.

2017-01-04 15:06 UTC, Blaidd-Drwg commented
Looks good to me. Could you undo your changes to `config/locales/de.default.yml`, since those are already part of #225 and are being reviewed there? When that is done, the PR can be merged :)

2017-01-04 15:55 UTC, Blaidd-Drwg approved these changes

2017-01-04 15:58 UTC, merged