185 3.23 application checking page
hpi-swt2/workshop-portal pull request #257
Opened 2017-01-06 13:08 UTC by aloeser

Add a application checking page, so participants can check their applications after creating/editing them

2017-01-06 18:48 UTC, bjrne commented
@tobiduer is this enough for #123 ?

2017-01-07 12:08 UTC, tobiduer commented
@bjrne: Yes. I closed the other issue.

2017-01-07 19:41 UTC, querenker requested changes
I especially like the use of the different tests 👍

2017-01-07 19:48 UTC, aloeser commented on app/views/application_letters/check.html.erb
> +  <%= habits.join(', ') %><br/>
We did ask him, and he said this behaviour is exactly what is wanted

2017-01-07 19:53 UTC, aloeser commented on app/views/application_letters/check.html.erb
> +  %>
So you would prefer to put do it in the controller and pass it as @habits? to the view?

2017-01-07 20:00 UTC, querenker commented on app/views/application_letters/check.html.erb
> +  %>
Maybe a model method for the application_letter that returns the habits as a list?

2017-01-07 23:08 UTC, aloeser commented
@tobiduer I dont think that #123 is completely done with this story. #123 also requires to replace the age-Field by birthday, which is not (yet) part of this user story.

2017-01-08 09:05 UTC, tobiduer commented
@aloeser: OK than please show the birthday instead of the age.

2017-01-08 10:32 UTC, ekrebs5 approved these changes

2017-01-08 11:02 UTC, timbasel approved these changes

2017-01-08 12:43 UTC, querenker approved these changes

2017-01-08 12:46 UTC, merged