event detail page. fixes #240
hpi-swt2/workshop-portal pull request #275
Opened 2017-01-10 12:31 UTC by LeaGe

changed appearance of event detail page

2017-01-13 19:27 UTC, corinnaj commented
The date looks out of place on some screen sizes, see picture below.

![screenshot from 2017-01-13 20-18-28](https://cloud.githubusercontent.com/assets/14113727/21942668/469e2cfe-d9ce-11e6-8810-9dc853633660.png)

2017-01-14 16:51 UTC, MasterCarl requested changes
In addition to the small change requested, it would be nice if you fixed the layout issue @corinnaj mentioned.

2017-01-14 16:51 UTC, MasterCarl commented on spec/models/date_range_spec.rb
> +    expect(date_range.to_s).to eq(I18n.l(Date.tomorrow))
This relies really strongly on the `on_single_day` trait returning the next day. Maybe compare to localization of just the start date?

2017-01-17 22:06 UTC, MasterCarl approved these changes

2017-01-18 11:00 UTC, merged