125 3.20 hide information
hpi-swt2/workshop-portal pull request #315
Opened 2017-01-11 18:12 UTC by Baschdl

This PR hides non-application-related information on the application letter page (for coaches and organizers) and displays a link to the profile of a applicant (for organisers and admins). Fixes #125

2017-01-13 15:33 UTC, frederike-ramin requested changes

2017-01-13 15:33 UTC, frederike-ramin commented on app/models/ability.rb
> +      can :show, Profile, user: { id: user.id }
That should already been done by line 37.

2017-01-13 15:33 UTC, frederike-ramin commented on app/models/ability.rb
> +      cannot :view_personal_details, ApplicationLetter, user: { id: !user.id }
Seems as if nobody could do that? There is no "can" for this ability in here..

2017-01-13 15:33 UTC, frederike-ramin commented on app/views/application_letters/show.html.erb
> +  <% if can? :view_personal_details, ApplicationLetter  %>
I really don't see how this relates to the US..I thought *nobody* should see that address? At least that's how I read it from the US.

2017-01-13 16:03 UTC, Baschdl commented on app/models/ability.rb
> +      cannot :view_personal_details, ApplicationLetter, user: { id: !user.id }
The role admin can view personal details

2017-01-13 16:03 UTC, Baschdl commented on app/views/application_letters/show.html.erb
> +  <% if can? :view_personal_details, ApplicationLetter  %>
Same as above, admin can see the address

2017-01-13 17:59 UTC, frederike-ramin commented on app/views/application_letters/show.html.erb
> +  <% if can? :view_personal_details, ApplicationLetter  %>
But why? I can't find that in the US description.

2017-01-13 18:26 UTC, Baschdl commented on app/views/application_letters/show.html.erb
> +  <% if can? :view_personal_details, ApplicationLetter  %>
I'll ask our PO @tobiduer

2017-01-14 12:59 UTC, Lando-L approved these changes

2017-01-14 18:56 UTC, querenker requested changes

2017-01-14 18:56 UTC, querenker commented on app/models/ability.rb
> +      cannot :check, ApplicationLetter
What is the difference between this line and line 53?

2017-01-14 18:56 UTC, querenker commented on app/models/ability.rb
> +      cannot :check, ApplicationLetter
Could this restrictions be moved to pupil? I think they would then also be valid for coach?

2017-01-14 19:16 UTC, aloeser commented on app/views/application_letters/show.html.erb
> +  <% if can? :view_personal_details, ApplicationLetter  %>
I'd agree with @frederike-ramin, as far as I know we never really cared about the admin role.
Moreover, if the admin wants to see the users address, he could as well look at the profile?

2017-01-14 19:19 UTC, aloeser requested changes

2017-01-14 19:19 UTC, aloeser commented on spec/features/application_letters_spec.rb
> +    expect(page).to have_text(@application_letter.user.profile.address)
If we need the admin role here, you should test that the school is present as well? Since you test its absence in the test above

2017-01-14 20:54 UTC, frederike-ramin commented on spec/features/application_letters_spec.rb
> +    expect(page).to have_text(@application_letter.user.profile.address)
No, the school is not actually displayed. never. Tobi just wanted to make sure, it also never will be in the future. (See US comments)

2017-01-15 11:41 UTC, querenker approved these changes

2017-01-16 18:56 UTC, Baschdl commented on app/views/application_letters/show.html.erb
> +  <% if can? :view_personal_details, ApplicationLetter  %>
@tobiduer confirmed that the admin should see the address. @frederike-ramin @aloeser Can you please update your review, if you don't find more problem?

2017-01-16 19:31 UTC, aloeser requested changes

2017-01-16 19:31 UTC, aloeser commented on spec/features/application_letters_spec.rb
> +    expect(page).to have_text(@application_letter.user.profile.address)
Well, than it should be tested that its not displayed for admins either?

2017-01-16 22:22 UTC, Baschdl commented
@aloeser Sorry, I can't comment your comment, @github is broken
<img width="844" alt="broken" src="https://cloud.githubusercontent.com/assets/3034832/22000958/74efee5a-dc42-11e6-86c4-f11028275ef7.png">

2017-01-16 22:23 UTC, bjrne commented on spec/features/application_letters_spec.rb
> +    expect(page).to have_text(@application_letter.user.profile.address)
Test

2017-01-16 22:24 UTC, Baschdl commented
@aloeser Admins should see the address/personal details. What do you mean?

2017-01-16 22:32 UTC, Baschdl commented on spec/features/application_letters_spec.rb
> +    expect(page).to have_text(@application_letter.user.profile.address)
Ah, it makes sense with context

2017-01-17 17:06 UTC, Baschdl commented
@aloeser @frederike-ramin Do you find more problems?

2017-01-17 18:23 UTC, frederike-ramin approved these changes
Well done. Sorry for the long review process.

2017-01-17 18:48 UTC, aloeser approved these changes

2017-01-17 19:07 UTC, merged