189 variable application fields input
hpi-swt2/workshop-portal pull request #323
Opened 2017-01-13 10:13 UTC by tom95

This adds the input for custom application fields on the event page. Field names are saved in an ordered array in the database so they can easily be output again and mapped to the user entered values, simply by maintaining the same order.

E.g.:
`["Lieblingsfarbe", "Lieblingstier"]` in `Event.custom_application_fields`

would correspond to

`["Blau", "Capybara"]` in `ApplicationLetter.custom_fields`

2017-01-13 10:26 UTC, bjrne commented on db/schema.rb
> -    t.integer  "status",                 default: 0
Is this line intended? (Somebody forgot to commit it earlier?)

2017-01-13 10:26 UTC, bjrne commented on db/schema.rb
> -    t.integer  "status",                 default: 0
Is this line intended? (Somebody forgot to commit it earlier?)

2017-01-13 10:31 UTC, tom95 commented on db/schema.rb
> -    t.integer  "status",                 default: 0
Yeah apparently, reran migrations after dropping and it stayed.

2017-01-13 12:12 UTC, cmfcmf commented
> Field names are saved in an ordered array in the database so they can easily be output again and mapped to the user entered values, simply by maintaining the same order.

This is how I solved it for my personal event management system years ago. It caused many errors and problems and was hard to maintain. I know it'd be more work but a proper entity schema would be a lot better. Things that can potentially break your implementation:
- Custom fields are deleted after somebody already applied
- Sort order of custom fields is changed after somebody applied
- Another custom field is added after somebody applied.

Just my two cents.

2017-01-13 12:13 UTC, cmfcmf commented
For the record, my system has the following schema:
1 event has n questions.
1 event has n application
1 application has n answers
1 question has n answers

2017-01-13 12:15 UTC, cmfcmf commented
You also run into problems once you extend the custom fields to have parameters themselves: Whether or not a field is editable, required, only allows integers, etc. Of course you can then store arrays of arrays of field options, but it only gets more messy and messy.

2017-01-13 12:34 UTC, tom95 commented
In order to avoid all of those problems our PO decided that all fields are immutable after creation. Using a more sophisticated data structure later on will only require changing very little code from this MR, so I think we can go with this smaller solution for the time being.

2017-01-13 14:54 UTC, cmfcmf commented
> In order to avoid all of those problems our PO decided that all fields are immutable after creation. Using a more sophisticated data structure later on will only require changing very little code from this MR, so I think we can go with this smaller solution for the time being.

I see. So when you create an event, you must be really careful not to add any wrong fields or include typos. If that's what's agreed upon for now, go ahead :)

2017-01-14 17:00 UTC, MasterCarl commented on app/models/event.rb
> +  serialize :custom_application_fields, Array
Very elegant solution

2017-01-14 17:10 UTC, MasterCarl commented on app/views/events/_show_event.html.erb
> +  <% if can? :manage, Event %>
`:manage` is the broadest permission, maybe `:create` would be more appropriate. Currently, it wouldn't make much of a difference, though.

2017-01-14 17:16 UTC, MasterCarl requested changes
Good work in general! I'd request just that one change.

2017-01-14 17:16 UTC, MasterCarl commented on spec/features/event_spec.rb
> +      expect(page).to_not have_text("Neues Feld hinzufügen")
This should be independent of translations

2017-01-17 22:06 UTC, MasterCarl approved these changes

2017-01-18 10:19 UTC, merged