233 3.3 event states
hpi-swt2/workshop-portal pull request #326
Opened 2017-01-13 18:18 UTC by frederike-ramin

Make event states more obvious by implementing a function that returns them.

--> needs to be used instead of the implicit request

2017-01-17 17:43 UTC, Lando-L requested changes

2017-01-17 17:43 UTC, Lando-L commented on app/models/event.rb
> +  # Returns the current statse of the event (draft-, application-, selection- and execution-phase)
Simple typo in state (statse)

2017-01-17 17:43 UTC, Lando-L commented on spec/models/event_spec.rb
> +    event.draft = false
Not absolute necessary because `event.draft = false` is default case

2017-01-17 17:43 UTC, Lando-L commented on spec/models/event_spec.rb
> +    event.draft = false
Same es line number 200

2017-01-17 17:43 UTC, Lando-L commented on spec/models/event_spec.rb
> +    event.draft = false
Or you could create a factory for each state of the event

2017-01-17 17:51 UTC, aloeser commented on spec/models/event_spec.rb
> +    event.draft = false
True, but I dont think its good to rely on the default values in factories, since they might be changed

2017-01-18 11:17 UTC, bjrne approved these changes
👍

2017-01-18 11:17 UTC, bjrne commented on app/models/application_letter.rb
> +
unnecessary whitespace change

2017-01-18 13:43 UTC, timbasel approved these changes

2017-01-18 18:37 UTC, Lando-L approved these changes

2017-01-18 18:50 UTC, merged