278 5.9 download material
hpi-swt2/workshop-portal pull request #329
Opened 2017-01-14 15:53 UTC by pinussilvestrus

- #278  an organizer or a coach can now download files of one event's material area

2017-01-14 16:44 UTC, Blaidd-Drwg commented
Cans for controller missing

2017-01-14 16:44 UTC, Fabian-Sommer requested changes

2017-01-14 16:44 UTC, Fabian-Sommer commented on spec/controllers/events_controller_spec.rb
> +      response.header['Content-Type'].should eql 'application/pdf'
This causes a deprecation warning whenever running tests. Use expect(...).to eq (...) instead.

2017-01-14 16:44 UTC, Fabian-Sommer commented on app/controllers/events_controller.rb
> +  end
You should check if the user has permission to download the file before sending it.

2017-01-15 23:08 UTC, Fabian-Sommer approved these changes

2017-01-15 23:36 UTC, merged