Request detail page
hpi-swt2/workshop-portal pull request #330
Opened 2017-01-14 16:29 UTC by MasterCarl

Closes #219.

2017-01-14 19:41 UTC, bjrne requested changes
I miss the schema file(?). The rest looks good.

2017-01-14 19:55 UTC, MasterCarl commented
@bjrne What do you mean? I ran `rake db:drop db:migrate` and saw no changes to `schema.rb`.

2017-01-15 00:24 UTC, bjrne commented
@MasterCarl Weird. You created a migration that adds a column and still don't get a change in `schema.rb`? I don't know how that's possible. Do you have any idea @tom95?

2017-01-15 10:03 UTC, MasterCarl commented
@bjrne Looks like the schema changes are already on the `dev` branch...

2017-01-15 10:12 UTC, bjrne commented
@MasterCarl true, it was you 😂 ba289f0.

2017-01-15 10:17 UTC, bjrne approved these changes
Beside this small change, everything looks good 👍

2017-01-15 10:17 UTC, bjrne commented on spec/features/request_spec.rb
> +        expect(request.status.to_sym).to eq(:accepted)
Tom pointed out that since this is a feature test, database access is really wanted here.

2017-01-15 19:29 UTC, bjrne commented
@MasterCarl #336 removed the status line from the `schema.rb` in order to have the right schema. You should now be able (and forced) to add it here again.

2017-01-15 22:22 UTC, merged