53 3.13 load email drafts
hpi-swt2/workshop-portal pull request #375
Opened 2017-01-21 13:13 UTC by TimBasel

Load Emails Templates

- Click on Template sets the hide_recipients radio buttons, subject and content field with template content

2017-01-21 15:32 UTC, ekrebs5 commented on spec/models/ability_spec.rb
> +  %i[pupil coach].each do |role|
These tests are already in the file, adding them would mean we have these tests 2-times

2017-01-21 17:08 UTC, Lando-L requested changes

2017-01-21 17:08 UTC, Lando-L commented on app/assets/javascripts/emails.js
> +function loadTemplate(elem) {
Anstatt die Funktion ins Html reinzuschreiben würde ich mehr jQuery Funktionen nutzen und so vorgehen:
```
$('.email-template.list-group-item').click(function() {
  var subject = $(this).find('template-subject')[0].text()
  var content = ...
});
```

2017-01-22 23:50 UTC, Lando-L approved these changes

2017-01-23 12:31 UTC, ekrebs5 submitted a review, later dismissed

2017-01-23 12:31 UTC, ekrebs5 commented on spec/models/ability_spec.rb
> +  %i[pupil coach].each do |role|
Now as review: 
These tests are already in the file, adding them would mean we have these tests 2-times

2017-01-24 20:08 UTC, frederike-ramin submitted a review, later dismissed
You didn't add any test, right? One feature test could do the job.

Plus, I agree with @ekrebs5 about the doubled tests.

2017-02-02 15:27 UTC, ekrebs5 approved these changes

2017-02-02 17:18 UTC, aloeser requested changes
just some small factory trait name changes, for consistency reasons

2017-02-02 17:18 UTC, aloeser commented on spec/factories/email_templates.rb
> +    trait :accepted do
you should call it acceptance

2017-02-02 17:18 UTC, aloeser commented on spec/factories/email_templates.rb
> +    trait :rejected do
you should call it rejection

2017-02-03 10:37 UTC, aloeser requested changes
Last small change, looks good otherwise :)

2017-02-03 10:37 UTC, aloeser commented on spec/features/email_spec.rb
> +    expect(page.find('#email_content').value).to eq(@template.content)
please also check for hide_recipients

2017-02-03 12:09 UTC, aloeser approved these changes

2017-02-03 12:09 UTC, merged