Rename Email Template statuses #242
hpi-swt2/workshop-portal pull request #401
Opened 2017-01-24 11:15 UTC by aloeser

This PR introduces better names for the email template status. Until now, the application letter statuses where used, now we have a better distinction between application letter status and template status

2017-01-24 16:35 UTC, querenker requested changes
Otherwise it looks good for me :)

2017-01-24 16:35 UTC, querenker commented on app/controllers/emails_controller.rb
> +    return :accepted
I think a case statement would be slightly better to read (and you get rid of the comment).

2017-01-24 16:35 UTC, querenker commented on app/controllers/emails_controller.rb
> +  def get_corresponding_application_letter_status
YARD annotation is missing

2017-01-24 16:35 UTC, querenker commented on app/controllers/emails_controller.rb
> +  def get_email_template_status
YARD annotation is missing

2017-01-24 16:35 UTC, querenker commented on app/controllers/emails_controller.rb
> +  def get_corresponding_application_letter_status
Currently maybe it looks a little bit overkill but a unit test should be provided, shouldn't it?

2017-01-24 17:32 UTC, aloeser commented on app/controllers/emails_controller.rb
> +  def get_email_template_status
Do you mean the documentation stuff? I think we agreed to write documentation for model functions, and this is just a (private) helper function inside the controller

2017-01-24 17:32 UTC, aloeser commented on app/controllers/emails_controller.rb
> +  def get_corresponding_application_letter_status
same

2017-01-24 17:37 UTC, aloeser commented on app/controllers/emails_controller.rb
> +  def get_corresponding_application_letter_status
Usually yes, but its a private controller helper. Calling this function alone doesnt make sense at all (and its not ment to be accessible from "outside". And I think that we never tested private helper methods (like e.g. event_params or such), so it seems inconsistent for me if we add a test for this. Instead, we test the public function that calls it.

2017-01-24 18:33 UTC, querenker commented on app/controllers/emails_controller.rb
> +  def get_email_template_status
You are right, a private method doesn't need documentation stuff

2017-01-24 18:50 UTC, querenker commented on app/controllers/emails_controller.rb
> +  def get_corresponding_application_letter_status
You are right, we rarely test private methods.  But I think test should beside guaraneing that the public interface works, minimize the effort to find the bug if something has broken (I don't like debugging). If the private method is broken a test would point directly to the broken location. I think for consistency reasons it is OK in this PR, but maybe we could talk about it later? @Baschdl?

2017-01-24 18:50 UTC, querenker approved these changes

2017-01-24 20:33 UTC, querenker commented on app/controllers/emails_controller.rb
> +  end
Just as little improvement. I think the case statement could also be written that way:
```ruby
return case params[:status]
       when "acceptance" then :accepted
       when "rejection" then :rejected
       else :accepted
       end
```

2017-01-24 20:38 UTC, aloeser commented on app/controllers/emails_controller.rb
> +  end
we can change it like that, looks easier to read

2017-01-29 12:08 UTC, ekrebs5 approved these changes

2017-01-29 16:30 UTC, merged