238 event description textfield
hpi-swt2/workshop-portal pull request #412
Opened 2017-01-25 14:15 UTC by corinnaj

Adjusted Multiline Placeholder so that it also works on other browsers, such as Firefox.

2017-01-27 09:20 UTC, tom95 requested changes

2017-01-27 09:20 UTC, tom95 commented on app/assets/javascripts/events.js
> +    .val(function() { return PLACEHOLDER; }).css('color', '#bbb')
This part would override existing content in the text field. You could use
```
.val(function(index, oldValue) { return oldValue || PLACEHOLDER; });
```
to fix this.

Additionally, jQuery() onload won't trigger for turbolinks navigation. You could try if turbolinks-jquery will fix that or alternatively use the same logic as found in `app/assets/javascripts/bootstrap.js` to make sure the code is triggered on turbolink loads as well.

2017-01-27 09:20 UTC, tom95 commented on app/views/events/_form.html.erb
> +        var PLACEHOLDER = '<%= I18n.t "events.description_placeholder" %>';
Maybe prefix the constant name as `EVENT_DESCRIPTION_PLACEHOLDER`, just in case anyone else was to introduce another placeholder somewhere.

2017-02-01 19:56 UTC, MasterCarl approved these changes
It works now, looks good.

2017-02-02 13:33 UTC, cmfcmf reviewed
I can't review this at the moment, because I'm getting the following error when trying to create a new event: 
> Showing /home/vagrant/hpi-swt2/app/views/events/_form.html.erb where line #46 raised:
> undefined local variable or method `participants_are_unlimited' for #<Event:0x007fa44fb90b90>
```
 def max_participants
    participants_are_unlimited ? Float::INFINITY : self[:max_participants]
  end
```

2017-02-02 16:00 UTC, bjrne commented
I guess this needs a new merge from dev, but I'm not sure I'm qualified to fix the conflicts. Could you give this a look @corinnaj @tom95?

2017-02-03 10:28 UTC, tom95 approved these changes

2017-02-03 10:35 UTC, merged