Add archive page for past events. Fixes #304.
hpi-swt2/workshop-portal pull request #414
Opened 2017-01-25 17:18 UTC by tom95

2017-01-25 17:29 UTC, bjrne commented on spec/factories/date_ranges.rb
> +        trait :force_past do
I'm not completely sure about RoR naming conditions, but I think "Entity :withX :withoutY" etc reads better than these titles.

2017-01-28 13:42 UTC, MasterCarl requested changes
Overall, this looks good

2017-01-28 13:42 UTC, MasterCarl commented on app/views/events/index.html.erb
> +      end if can? :new, Event %>
Please add a newline between `end` and `if`

2017-01-28 13:42 UTC, MasterCarl commented on app/views/events/archive.html.erb
> +      t('.new', :default => t('events.all_events'))
Why is the translation key `new`?

2017-01-28 13:42 UTC, MasterCarl commented on app/controllers/events_controller.rb
> +    def add_event_query_conditions(query)
I'm not too happy with the naming here, but then again, I don't have any better ideas, either.

2017-02-01 07:33 UTC, tom95 commented on app/views/events/index.html.erb
> +      end if can? :new, Event %>
this is actually a "suffix" if. believe me if I tell you that it was even more confusing the other way around

2017-02-01 07:50 UTC, corinnaj commented on app/controllers/events_controller.rb
> +    def add_event_query_conditions(query)
I think the naming is fine.

2017-02-01 08:46 UTC, MasterCarl commented on app/views/events/index.html.erb
> +      end if can? :new, Event %>
Oh, alright

2017-02-01 08:46 UTC, MasterCarl approved these changes

2017-02-01 08:50 UTC, merged