1st...
hpi-swt2/workshop-portal pull request #415
Opened 2017-01-25 17:29 UTC by radscheit

2017-01-25 20:28 UTC, Blaidd-Drwg requested changes

2017-01-25 20:28 UTC, Blaidd-Drwg commented on app/views/events/participants.html.erb
> +        <%= link_to t('events.participants.print_habits'),
Indentation

2017-01-25 20:28 UTC, Blaidd-Drwg commented on app/views/events/_participants_modal.html.erb
> +            :formtarget => "_blank" ) %>
Why do you use `formtarget` here and `target` in the other `submit_tag`?
Also, mixing the two syntaxes for hashes looks weird, please keep it consistent.

2017-01-25 20:28 UTC, Blaidd-Drwg commented on app/views/events/participants.html.erb
> +        <button class="btn btn-default btn-sm" type="button" data-toggle="modal" data-target="#print_participant_modal" id="open_print_modal">Teilnehmerliste (PDF)</button>
Please I18n-ify this while you're at it :wink:

2017-01-25 20:29 UTC, radscheit commented on app/views/events/_participants_modal.html.erb
> +            :formtarget => "_blank" ) %>
formtarget follows the specific syntax description for submit tag

2017-01-25 20:58 UTC, Blaidd-Drwg commented on app/views/events/_participants_modal.html.erb
> +            :formtarget => "_blank" ) %>
The `submit_tag` in `app/views/events/participants.html.erb` has the normal target though :confused:

2017-01-25 21:09 UTC, radscheit commented on app/views/events/_participants_modal.html.erb
> +            :formtarget => "_blank" ) %>
OK: http://www.w3schools.com/tags/att_button_formtarget.asp

2017-01-27 20:50 UTC, Blaidd-Drwg commented on app/views/events/participants.html.erb
> +                :target => '_blank' %>
This link doesn't need to open in a new tab, it loads an HTML page.

2017-01-27 22:03 UTC, Blaidd-Drwg approved these changes

2017-01-27 22:03 UTC, merged