319 workshop choice bar
hpi-swt2/workshop-portal pull request #438
Opened 2017-01-28 16:04 UTC by radscheit

2017-02-03 14:42 UTC, pinussilvestrus requested changes
![image](https://cloud.githubusercontent.com/assets/9433996/22595321/4a1d2d3a-ea27-11e6-8c19-7052d99d39b3.png)

this doesn't look correct or?

2017-02-03 14:42 UTC, pinussilvestrus commented on app/assets/stylesheets/requests.css
> +margin-top:10px;
can you add tabs in this stylesheet?

2017-02-03 14:42 UTC, pinussilvestrus commented on config/locales/de.requests.yml
> +      lead_paragraph: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laborum fugiat quasi expedita distinctio, suscipit, eaque deleniti similique eveniet in accusantium voluptas blanditii
I don't know whether there is another story for it, but wouldn't it be better if here is a better content than Lorem ipsum?

2017-02-08 16:51 UTC, radscheit commented on config/locales/de.requests.yml
> +      lead_paragraph: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laborum fugiat quasi expedita distinctio, suscipit, eaque deleniti similique eveniet in accusantium voluptas blanditii
Done.

2017-02-08 21:05 UTC, pinussilvestrus approved these changes

2017-02-08 22:38 UTC, merged