41 4.16 application confirmation
hpi-swt2/workshop-portal pull request #453
Opened 2017-02-01 13:19 UTC by Raandom

2017-02-01 13:43 UTC, c0rnyc0rny requested changes

2017-02-01 13:43 UTC, h0rnyc0rny commented on config/locales/de.application_letters.yml
> +        content: "Hallo, \n\rDu hast dich erfolgreich fuer  {{semimar_name}} beworben. Deine Bewerbung wird jetzt bearbeitet. Fuer weitere Information besuche das Workshop Portal. Viele Grueße, das H
If possible use "ü" instead of "ue"

2017-02-01 13:51 UTC, c0rnyc0rny approved these changes

2017-02-01 13:51 UTC, merged

2017-02-01 14:54 UTC, bjrne commented on config/locales/de.application_letters.yml
> +        sender: "workshop@hpi.de"
I would have liked to see the usage of the default value or any other user changeable email here

2017-02-01 14:54 UTC, bjrne commented on config/locales/de.application_letters.yml
> +        content: "Hallo, \n\rDu hast dich erfolgreich für  {{semimar_name}} beworben. Deine Bewerbung wird jetzt bearbeitet. Für weitere Information besuche das Workshop Portal. Viele Grüße, das HPI
`semimar_name`

2017-02-01 14:55 UTC, bjrne commented
@Raandom @h0rnyc0rny

2017-02-03 10:12 UTC, cmfcmf commented
This has broken stuff. Part of it was fixed by #490. Another issue is #492.

2017-02-03 17:43 UTC, bjrne commented
@Raandom @h0rnyc0rny It would be nice if you'd actually look at your mentions. You can unsubscribe from the general notifications, the level should then lower to an acceptable one. Or you could visit https://github.com/issues/mentioned and https://github.com/pulls/mentioned a bit more. Please.

2017-02-03 18:00 UTC, Raandom commented
This didnt break anything That wasnt Broken Before. Fixing the typo tomorrow.