320 picture upload
hpi-swt2/workshop-portal pull request #501
Opened 2017-02-03 13:42 UTC by corinnaj

Finally added image upload, so events can have pictures

2017-02-03 15:15 UTC, GoesOnTangents approved these changes

2017-02-03 16:13 UTC, cmfcmf requested changes
Please add the new dependencies to the Vagrantfile.
https://github.com/hpi-swt2/workshop-portal/blob/dev/Vagrantfile#L28

2017-02-03 20:20 UTC, cmfcmf commented on Vagrantfile
> +    apt-get install imagemagick
-y is missing :)

2017-02-04 12:18 UTC, cmfcmf approved these changes

2017-02-04 13:50 UTC, merged

2017-02-04 19:55 UTC, Baschdl commented
@corinnaj This test doesn't work on my machine.

```
Event create page should not allow uploading images that are too small
     Failure/Error: expect(page).to have_text(I18n.t "events.errors.image_too_small")
       expected to find text "Das ausgewählte Bild muss mindestens 200 x 155 Pixel groß sein" in "Toggle navigation VeranstaltungenWorkshop anfragen Einloggen Veranstaltung erstellen Achtung. In einem Feld ist ein Fehler aufgetreten. Korrigiere den Fehler, um fortzufahren Veranstaltungstyp Öffentlich Privat Entwurf Speichern Veröffentlichen Name Beschreibung Dieser Editor unterstüzt Markdown Bild translation missing: en.errors.messages.mini_magick_processing_error Lokale Datei hochladen Maximale Teilnehmerzahl Zeitspanne To × Zeitspanne hinzufügen Veranstalter Kenntnisstand Bewerbungsschluss Eigene Bewerbungs-Felder Neues Feld hinzufügen Die eigenen Felder für die Bewerbung können nach dem ersten Speichern nicht mehr geändert werden. Impressum | Hasso-Plattner-Institut © 2017 Hasso-Plattner-Institut Companion Cube <3"
     # ./spec/features/event_spec.rb:267:in `block (3 levels) in <top (required)>'
```

2017-02-04 20:23 UTC, Baschdl commented
The new Vagrantfile resolved it