send rejection mail also to alternatives #526
hpi-swt2/workshop-portal pull request #536
Opened 2017-02-06 23:01 UTC by ekrebs5

Rejection mails are also send to alternatives

old functions that were adjusted:
- if you send acceptions, it switches directly to execution if there are no rejection or alternatives
- the alternatives also get the notifiction send flag

2017-02-07 13:47 UTC, frederike-ramin requested changes

2017-02-07 13:47 UTC, frederike-ramin commented on app/controllers/emails_controller.rb
>        @event.set_status_notification_flag_for_applications_with_status(application_letter_status)
Maybe this should be within the if clause. If you send emails with a status other than acceptance/rejection, you don't want the flag to be updated.

2017-02-07 13:47 UTC, frederike-ramin commented on app/controllers/emails_controller.rb
> +        if not @event.has_rejected_or_alternative_participants_without_status_notification?
If you just replace that by a simple or, you can save up the whole function.

2017-02-07 22:56 UTC, timbasel approved these changes
Looks good to me

2017-02-08 07:53 UTC, frederike-ramin approved these changes

2017-02-08 07:54 UTC, merged