58 3.16 personal email refactoring
hpi-swt2/workshop-portal pull request #622
Opened 2017-02-10 10:07 UTC by TimBasel

Refactoring of the email system-

- Moved Attachment creation out of  the email model
- Unified the status variable in Email

2017-02-11 12:59 UTC, aloeser requested changes
I dont think we want to go back to accepted and rejected for email template states.
We renamed them from accepted to acceptance in an earlier PR, in order to avoid mixing two things that are equal by accident, but dont mean the same. Also, you rather send an acceptance than accepted mail.

And I'm not sure if I would rename get_email_template_status to get_status, the first one seems more precise to me

2017-05-12 10:20 UTC, ekrebs5 commented on app/models/agreement_letter.rb
> +  def self.get_attachment
I would leave this as get agreement letter attachment, since it is more precise and other attachments in emails are very likely

2017-05-12 10:22 UTC, ekrebs5 approved these changes

2017-05-15 20:35 UTC, aloeser approved these changes

2017-05-15 23:17 UTC, merged