refactor application letter factory
hpi-swt2/workshop-portal pull request #634
Opened 2017-05-10 06:59 UTC by aloeser

we now use traits instead of inheritance

2017-05-10 07:29 UTC, aloeser commented
One thing I'm not sure about is whether to put the traits into or below the factories, like
```
factory :application_letter do

    trait :accepted do
          status :acccepted
    end
end

trait :rejected do
    status :rejected
end```

Any comments or ideas?

2017-05-10 07:35 UTC, aloeser commented
Nevermind, 1min debugging with `rails console` helped. Putting them below factories makes them globally available, so that you can run `FactoryGirl.build(:event, :accepted)` which doesnt make sense.
I'll change it soon

2017-05-10 19:32 UTC, querenker requested changes
The traits are very nice 👍

2017-05-10 19:32 UTC, querenker commented on spec/controllers/email_controller_spec.rb
> +        @application = FactoryGirl.create(:application_letter, :accepted, event: @event, user: FactoryGirl.build(:user))
Is the user association in this create call even necessary? I think [this association definition](https://github.com/hpi-schuelerklub/workshop-portal/blob/35d5b8dd50ac72141dd33b35200a3682b5712588/spec/factories/application_letters.rb#L22) should be enough?

2017-05-10 19:32 UTC, querenker commented on spec/controllers/email_controller_spec.rb
> +        @application = FactoryGirl.create(:application_letter, :rejected, event: @event, user: FactoryGirl.build(:user))
User association again

2017-05-11 17:59 UTC, querenker approved these changes

2017-05-13 08:23 UTC, bjrne approved these changes
Good 🏃‍♀️

2017-05-13 08:23 UTC, merged