Applicants Overview for Events (formerly known as Workshops)
hpi-swt2/workshop-portal pull request #64
Opened 2016-11-24 11:11 UTC by TimBasel

This is basic implementation of the Applicants Overview for the Events Page.

2016-11-24 12:09 UTC, frederike-ramin commented on app/models/profile.rb
> +  def self.human_attribute_name(*args)
Isn't that exactly the type of hardcoding internationalism that we wanted to avoid?

2016-11-24 12:27 UTC, chrisma commented on spec/models/profile_spec.rb
> +    expect(profile.name).to eq("Karl Doe")
What happens when the factory is changed and creates different first and last names?
What about `expect(profile.name).to eq("#{profile.first_name} #{profile.last_name})`

2016-11-24 12:29 UTC, chrisma commented on spec/views/events/show.html.erb_spec.rb
> +    expect(rendered).to have_css("th", :text => "Status")
I18n?

2016-11-24 12:57 UTC, TimBasel commented on app/models/profile.rb
> +  def self.human_attribute_name(*args)
Yes, will be updated in the next version. But I think it isn't necessarily required for the Pull Request.

2016-11-24 12:59 UTC, chrisma commented on app/models/user.rb
> +    case args[0].to_s
Why `case`?

2016-11-24 13:14 UTC, TimBasel commented on app/models/user.rb
> +    case args[0].to_s
Was planed to be more extensive. Will be updated with all the localization changes

2016-11-24 13:16 UTC, TimBasel commented on spec/models/profile_spec.rb
> +    expect(profile.name).to eq("Karl Doe")
Yes should be updated, together with the `15` in the test before

2016-11-24 13:33 UTC, TimBasel commented on spec/views/events/show.html.erb_spec.rb
> +    expect(rendered).to have_css("th", :text => "Status")
See other comment about localization

2016-11-24 19:34 UTC, querenker commented
Although Code Climate can't (currently) check the pull request automatically, it can be triggered through the web view. Maybe you can take a look :)

https://codeclimate.com/github/hpi-swt2/workshop-portal/compare/23_3.3_ApplicantsOverview#issues

2016-11-25 13:54 UTC, TimBasel commented
Pull Request now features the updated localization, the right management for pupil, coach, organizer

2016-11-25 14:54 UTC, querenker requested changes
Beside these little changes it looks good to me

2016-11-25 14:54 UTC, querenker commented on app/models/profile.rb
> +    now.year - birth_date.year - (birth_date.to_date.change(:year => now.year) > now ? 1 : 0)
If a person was born at the 29th February on a leap year and the current year is not a leap year. I think `birth_date.to_date.change(:year => now.year)` will break. Can you add this test case?

2016-11-25 14:54 UTC, querenker commented on app/views/application_letters/show.html.erb
> +  <dt><strong><%= Profile.human_attribute_name(:gender) %>:</strong></dt>
Should all dt-elements be strong? Maybe the style could than be adjusted in a CSS-file?

2016-11-25 14:54 UTC, querenker commented on config/locales/en.events.yml
> +      title: "Applicants for"
`title: "Applicants for %{title}"`?

2016-11-25 14:54 UTC, querenker commented on spec/features/events_spec.rb
> +    visit event_path(@event)
The above code is nearly identical in all this tests. Maybe it can be factored out?

2016-11-25 15:02 UTC, TimBasel commented on config/locales/en.events.yml
> +      title: "Applicants for"
yes, english was not updated. will do.

2016-11-26 15:57 UTC, TimBasel commented on app/views/application_letters/show.html.erb
> +  <dt><strong><%= Profile.human_attribute_name(:gender) %>:</strong></dt>
used to stay consistent with the exististing implementation in the views

2016-11-26 15:59 UTC, TimBasel commented
Incorrect Age method fixed, refactoring of feature test and removal of not required english language support

2016-11-26 16:12 UTC, querenker approved these changes

2016-11-26 16:22 UTC, querenker commented on app/models/profile.rb
> +    now.year - birth_date.year - ((now.month > birth_date.month || (now.month == birth_date.month && now.day >= birth_date.day)) ? 0 : 1)
Thanks, now the bug should be fixed (+1 for adding test case). Maybe this algorithm could be separated by using descriptive intermediate variables. At least for me it needed some time to understand it. But I think it is "okish".

2016-11-26 17:20 UTC, aloeser requested changes

2016-11-26 17:20 UTC, aloeser commented on app/models/user.rb
> +  # @return [Int] of number of accepted applications
What about temporary accepted applications?
Is it intended those are included here? (@tobiduer)

If not, I suggest to update the code (even if it means you need to change the database to figure out whether an accept/reject is final), or at least add a TODO to indicate this function needs to be updated later.

2016-11-26 17:20 UTC, aloeser commented on app/models/user.rb
> +  def rejected_application_count
same as with accepted_application_count

2016-11-26 17:20 UTC, aloeser commented on config/locales/de.users.yml
> +        accepted_application_count: "Anzahl der angenommene Bewerbungen"
"n" missing
one line lower too

2016-11-26 17:20 UTC, aloeser commented on spec/views/application_letters/show.html.erb_spec.rb
> +  it "renders appllicant's attributes" do
"l" too much

2016-11-26 17:57 UTC, tobiduer commented on app/models/user.rb
> +  # @return [Int] of number of accepted applications
As discussed on Slack, the currently displayed camp does not count, but temporary acceptance / rejection of other camps can count

2016-11-26 23:56 UTC, aloeser approved these changes

2016-11-26 23:57 UTC, merged

2016-11-28 23:25 UTC, bjrne commented on Gemfile.lock
> -   ruby 2.2.2p95
Is there a reason for this? Compare with [this](https://github.com/hpi-swt2/workshop-portal/pull/51#pullrequestreview-9704030)