505 past date validations
hpi-swt2/workshop-portal pull request #649
Opened 2017-05-22 12:57 UTC by bjrne

Closes #505.

2017-06-04 12:19 UTC, ekrebs5 approved these changes

2017-06-04 12:26 UTC, querenker requested changes
I think this one test is worth a discussion, but otherwise it looks good to me 👍

2017-06-04 12:26 UTC, querenker commented on spec/features/event_spec.rb
> +    it "should allow dates in the past" do
I am not sure if this test communicates the right thing. If I were a new developer to this project I would ask what's the purpose of creating events in the past. Allowing old events to edit makes sense, but creating "old" events?

2017-06-04 20:30 UTC, bjrne commented on spec/features/event_spec.rb
> +    it "should allow dates in the past" do
Wow, didn't think of that. I like the idea, would changing the test action to editing an existing event and saving it without errors be what you suggested?

2017-06-27 19:20 UTC, querenker approved these changes

2017-06-27 19:21 UTC, querenker commented on spec/features/event_spec.rb
> +    it "should allow dates in the past" do
Looks good to me 👍

2017-07-01 19:50 UTC, merged