Allow login via HPI OpenID
hpi-swt2/workshop-portal pull request #663
Opened 2017-06-05 09:11 UTC by cmfcmf

This is part of #637.

All HPI users are autmatically promoted to coaches.

2017-06-05 19:59 UTC, bjrne approved these changes
Looks good 👑

2017-06-05 19:59 UTC, bjrne commented on config/routes.rb
> +      :omniauth_callbacks => "users/omniauth_callbacks"
Can you explain what these lines are for? :)

2017-06-06 11:13 UTC, cmfcmf commented on config/routes.rb
> +      :omniauth_callbacks => "users/omniauth_callbacks"
They tell Devise to use our controllers (inside `app/controllers`) for `:registrations` and `:omniauth_callbacks`.

2017-06-18 17:59 UTC, corinnaj approved these changes
Looks good to me, I only found some very minor things and a few questions.

2017-06-18 17:59 UTC, corinnaj commented on Gemfile
> +#gem 'devise_openid_authenticatable'
This comment can probably be deleted

2017-06-18 17:59 UTC, corinnaj commented on Gemfile.lock
> +    builder (3.2.3)
Out of curiosity, why are there so many version changes?

2017-06-18 17:59 UTC, corinnaj commented on app/models/user.rb
> +      # user.name = auth.info.first_name + " " + auth.info.last_name
Another comment, that is probably not needed

2017-06-18 17:59 UTC, corinnaj commented on spec/features/user_hpiopenid_spec.rb
> +RSpec.feature "Account creation vis HPI OpenID", :type => :feature do
There's a typo here: vis should probably be via

2017-06-18 17:59 UTC, corinnaj commented on spec/views/users/users_sessions_new.html.erb_spec.rb
> +    without_partial_double_verification do
Can you explain to me what lines 6 and 7 do?

2017-06-18 18:27 UTC, corinnaj requested changes
I get an error when I try to create a new account with OpenID on my machine: 
```ActiveRecord::RecordInvalid - Gültigkeitsprüfung ist fehlgeschlagen: E-Mail-Adresse Feld ist leer: bitte fülle es aus, um fortzufahren.```

2017-06-19 08:28 UTC, bjrne commented
That's weird because it works on heroku. Did you set up your openID Account correctly?

2017-06-19 08:39 UTC, corinnaj commented
For me it doesn't work on Heroku either. We tried it with @aloeser account as well and got the same error:
![screenshot from 2017-06-19 10-34-07](https://user-images.githubusercontent.com/14113727/27276395-6908fcc8-54db-11e7-8ef0-5e3f61e76042.png)

2017-06-20 09:13 UTC, bjrne commented
Okay, since this error was tied to a wrong configuration on the openID provider site I'd suggest to merge this for now and make a separate issue for an explanation along with a proper error message @corinnaj @aloeser ?

2017-06-20 11:31 UTC, corinnaj approved these changes

2017-06-20 11:33 UTC, merged

2017-06-20 12:18 UTC, bjrne commented
```
2017-06-20T12:15:58.220488+00:00 app[web.1]: Completed 500 Internal Server Error in 4ms (ActiveRecord: 1.0ms)
2017-06-20T12:15:58.232738+00:00 app[web.1]: 
2017-06-20T12:15:58.232740+00:00 app[web.1]: ActiveRecord::StatementInvalid (PG::UndefinedColumn: ERROR:  column users.provider does not exist
2017-06-20T12:15:58.232740+00:00 app[web.1]: LINE 1: SELECT  "users".* FROM "users" WHERE "users"."provider" = 'h...
2017-06-20T12:15:58.232741+00:00 app[web.1]:                                              ^
2017-06-20T12:15:58.232742+00:00 app[web.1]: : SELECT  "users".* FROM "users" WHERE "users"."provider" = 'hpiopenid' AND "users"."uid" = 'https://openid.hpi.uni-potsdam.de/user/bjarne.sievers'  ORDER BY "users"."id" ASC LIMIT 1):
2017-06-20T12:15:58.232742+00:00 app[web.1]:   app/models/user.rb:49:in `from_omniauth'
2017-06-20T12:15:58.232743+00:00 app[web.1]:   app/controllers/users/omniauth_callbacks_controller.rb:5:in `hpiopenid'
2017-06-20T12:15:58.232743+00:00 app[web.1]: 
2017-06-20T12:15:58.232744+00:00 app[web.1]: 
2017-06-20T12:15:58.233226+00:00 heroku[router]: at=info method=GET path="/users/auth/hpiopenid/callback?_method=post&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.op_endpoint=https%3A%2F%2...
```